export const spaceFacts = [
  'There are approximately 10,000 stars in the observable universe per each grain of sand on Earth. With there being roughly 7.5 sextillion grains of sand on Earth that makes the number of stars in the universe approximately 7.5 septillion, or 75,000,000,000,000,000,000,000,000.',
  'The sun makes up 99.86% of the mass in our solar system.',
  'There are more possible iterations of a game of chess than there are atoms in the observable universe.',
  'The first living creature sent into space was a dog named Laika from the Soviet Union in 1957.',
  'The largest asteroid known in our solar system is Ceres, with a diameter of about 590 miles.',
  'The International Space Station is the largest manned object ever sent into space, and it travels around the Earth at a speed of 27,580 kilometers per hour.',
  'The Great Red Spot on Jupiter is a giant storm that has been raging for at least 400 years.',
  "A black hole isn't a hole at all, but rather a point in space with a gravitational pull so strong that nothing, not even light, can escape it.",
  'The Hubble Space Telescope is able to see back in time, as it can observe objects that are billions of light years away from us.',
  'The Milky Way galaxy is estimated to contain between 100 billion and 400 billion stars.',
  'The moon is moving away from Earth at a rate of about 1.5 inches (4 cm) per year.',
  "In 1969, Neil Armstrong became the first human to set foot on the moon, famously declaring, 'That's one small step for man, one giant leap for mankind.'",
  'Jupiter is the fastest rotating planet in our solar system, completing a full rotation on its axis in just under 10 hours.',
  'The coldest place in the universe that we know of is the Boomerang Nebula, which has a temperature of -458 degrees Fahrenheit (-272 degrees Celsius).',
  'The Kuiper Belt is a region of space beyond Neptune that contains many small, icy objects, including Pluto and several dwarf planets.',
  'Venus has a thick, toxic atmosphere that traps heat and creates a runaway greenhouse effect, making it the hottest planet in our solar system with surface temperatures that can reach up to 864 degrees Fahrenheit (462 degrees Celsius).',
  'The asteroid belt is located between the orbits of Mars and Jupiter, and contains hundreds of thousands of small rocky objects.',
  'The universe is thought to be around 13.8 billion years old, and it is expanding at an accelerating rate.',
  "The largest mountain in our solar system is Olympus Mons, which is located on Mars and stands at a towering height of 13.6 miles (22 kilometers). That's roughly three times taller than Mount Everest, the tallest mountain on Earth.",
  'The Apollo 11 mission, which landed humans on the moon for the first time, was almost aborted due to an unexpected computer error.',
  'A day on Mars is only slightly longer than a day on Earth, lasting 24 hours and 39 minutes.',
  'Astronomers believe that there may be more than 100 billion planets in our Milky Way galaxy alone, many of which may be capable of supporting life as we know it.',
  'The first American woman in space was Sally Ride, who flew on the space shuttle Challenger in 1983.',
  'Neutron stars are incredibly dense objects that can result from the collapse of a massive star, and they can spin up to several hundred times per second.',
  "Saturn's rings are made up of billions of individual pieces of ice and rock, ranging in size from tiny specks to large boulders.",
  'The James Webb Space Telescope, launched in 2021, is the largest, most powerful space telescope ever built, and is able to see further into space and back in time than any telescope before it.',
  'Astronomers estimate that the observable universe contains around 2 trillion galaxies, each containing billions or trillions of stars.',
  'The first photograph of a black hole was captured in 2019 by the Event Horizon Telescope, a global network of telescopes that took images of the supermassive black hole at the center of the galaxy M87.',
  'The largest moon in our solar system is Ganymede, which is even bigger than the planet Mercury.',
  'The universe is mostly made up of dark matter and dark energy, which are invisible and do not interact with light or matter in the same way as ordinary matter.',
  'Comets are icy objects that originate from the outer reaches of the solar system, and can develop long, glowing tails when they come close to the sun.',
  "The Parker Solar Probe, launched in 2018, is the closest any spacecraft has ever come to the sun, and will help scientists better understand the sun's magnetic field and how it affects space weather.",
  'The Great Attractor is a mysterious gravitational anomaly located in the direction of the constellation Centaurus that is pulling the Milky Way and hundreds of thousands of other galaxies towards it.',
  'The fastest object ever launched by humans was the Parker Solar Probe, which reached a speed of 430,000 miles per hour (700,000 kilometers per hour) as it made its closest approach to the sun.',
  'Astronomers believe that there may be as many as 500 million potentially habitable planets in our Milky Way galaxy alone.',
  'A gamma-ray burst is a powerful explosion that can release as much energy in a few seconds as the sun will over its entire lifetime.',
  "The Cassini spacecraft, which explored Saturn and its moons from 2004 to 2017, discovered liquid lakes on the surface of Titan, Saturn's largest moon.",
  'The Kuiper Belt object Ultima Thule, which was explored by the New Horizons spacecraft in 2019, is the farthest object ever visited by a human-made spacecraft, located over 4 billion miles (6.5 billion kilometers) from Earth.',
  'A day on Venus is longer than a year on Venus. It takes 243 Earth days for Venus to rotate once on its axis, but only 225 Earth days to orbit the sun.',
  "Astronauts on the International Space Station can see up to 15 sunrises and sunsets every day due to the station's high orbital speed.",
  'Black holes are not actually black, but emit radiation, known as Hawking radiation, which causes them to slowly evaporate over time.',
  'The Andromeda Galaxy, the closest galaxy to our Milky Way, is on a collision course with our galaxy and will eventually merge with it in about 4.5 billion years.',
  'Neutron stars are incredibly dense objects that are created when a massive star explodes in a supernova. A single teaspoon of neutron star material would weigh about 900 times the weight of the Great Pyramid of Giza.',
  "The term 'astronaut' comes from the Greek words 'astron', meaning star, and 'nautes', meaning sailor.",
  'The Boötes Void, also known as the Great Void, is a region of space that is almost entirely empty of galaxies, spanning over 250 million light-years.',
  'The largest asteroid in our solar system, Ceres, is also classified as a dwarf planet and is located in the asteroid belt between Mars and Jupiter.',
  'The Voyager 1 spacecraft, launched in 1977, is the farthest human-made object from Earth and has traveled over 14 billion miles (23 billion kilometers) from the sun.',
  'The Perseid meteor shower, which occurs annually in August, is caused by debris left behind by the Comet Swift-Tuttle and appears to radiate from the constellation Perseus.',
  'Mercury & Venus are the only 2 planets in our solar system that have no moons.',
  'If a star passes too close to a black hole, it can be torn apart. This is known as a tidal disruption event.',
  'Our solar system is over 4.5 billion years old and formed from a dense cloud of interstellar gas and dust.',
  'Every atom of oxygen in our lungs, of carbon in our muscles, of calcium in our bones, of iron in our blood - was created inside a star before the solar system was born. We are walking, talking stardust.',
  'A light year is a unit of distance, not time. It is the distance that light can travel in one year, or about 6 trillion miles (10 trillion kilometers).',
  'The sun is about 4.6 billion years old and is expected to remain in its current state for another 5 billion years before it runs out of fuel and becomes a red giant.',
  'The Milky Way galaxy is about 100,000 light-years across. It would take a modern spacecraft about 450,000,000 years to reach the center of the galaxy.',
  'If you travel at the speed of light, you no longer experience the passage of time. This is known as time dilation.',
  'The footprints left by astronauts on the moon will remain there for millions of years, as there is no wind or water on the moon to erode them.',
  'As of February 2023, Jupiter has 95 moons, the most of any planet in our solar system. The moons form a satellite system known as the Jovian system.',
  'The largest known star in the universe, UY Scuti, has a radius over 1,700 times that of the sun.',
  'The color of a star can reveal its temperature. For example, blue-white stars are hotter than red ones.',
  'Stars are powered by nuclear fusion, in which lighter elements are fused into heavier ones, releasing a tremendous amount of energy in the process.',
  'The sun, a typical star, has a lifespan of about 10 billion years and is currently about halfway through its life.',
  'Some stars, known as pulsars, emit regular pulses of radiation and are among the most precise natural timekeepers known to science.',
  'When a star dies, it can explode in a supernova, releasing more energy in a single moment than our sun will produce in its entire lifetime.',
  'The nearest star to our solar system, Proxima Centauri, is over 4 light-years away and would take tens of thousands of years to reach with current spacecraft technology.',
  'The North Star, Polaris, is actually a multiple star system consisting of three stars, with the main star being a supergiant over 4,000 times as bright as the sun.',
  "Some stars, known as brown dwarfs, are too small to sustain nuclear fusion and never become true stars, but are instead often referred to as 'failed stars'.",
  'The study of stars and their properties is known as astronomy, and the study of the universe as a whole is known as cosmology.',
  'Astronomers estimate that there are over 100 billion stars in the Milky Way galaxy alone, and rouglhly 2 trillion galaxies in the observable universe.',
  "The term 'nova' refers to a sudden brightening of a star, which can be caused by a runaway nuclear reaction or the accretion of material from a companion star.",
  "We know more about the surface of Mars than we do about the ocean floor on Earth, as it's easier to send spacecraft to Mars than to explore the depths of our own planet.",
  'The boundary of outer space is known as the Kármán line, and is located 62 miles (100 kilometers) above sea level.',
  'We always see the same side of the moon from Earth, as the moon rotates on its axis at the same rate that it orbits the Earth. This is known as tidal locking.',
  'The oldest view of space, taken by the James Webb Space Telescope, shows a galaxy that is over 13 billion light-years away. The light particles that make up the image started their journey over 8 billion years before the Earth was even formed.',
  'Red dwarfs are the most common type of star in the Milky Way galaxy, accounting for over 70% of all stars.',
  "The stars in the constellation Orion form an asterism known as the 'Orion's Belt', which is one of the most recognizable star patterns in the sky.",
  'The surface temperature of the sun is around 5,500 degrees Celsius (9,932 degrees Fahrenheit), but the temperature in its core can reach over 15 million degrees Celsius (27 million degrees Fahrenheit).',
  'In 1572, the astronomer Tycho Brahe observed a supernova in the Milky Way that was brighter than Venus and was visible during the day for several weeks.',
  'A starquake is a sudden release of energy in the form of seismic waves, similar to an earthquake, that can occur in certain types of stars.',
  'The biggest stars are not necessarily the brightest. The brightness of a star also depends on its distance from Earth and the amount of interstellar dust between the star and us.',
  'Some stars, known as variable stars, can undergo periodic changes in brightness, which can be used by astronomers to measure distances to other galaxies.',
  "The stars in the constellation Cygnus form a pattern known as the 'Northern Cross', which is visible in the summer months in the Northern Hemisphere.",
  "The sun's magnetic field undergoes a complete reversal every 11 years, which can have effects on Earth's climate and weather patterns.",
  'Stars that are less massive than the sun are known as red dwarfs and can have lifespans of trillions of years, much longer than the current age of the universe. The dim red dwarfs will eventually become the last stars in the universe.',
  'The acceleration of the expansion of the universe could eventually lead to a phenomenon known as the "cosmic event horizon", in which all galaxies outside of our own will be moving away from us faster than the speed of light, making them impossible to observe. If this happens, any future intelligent life in the universe will never know that other galaxies exist.',
  'Empty space is not actually empty. According to quantum mechanics, empty space is filled with virtual particles that constantly pop in and out of existence.',
  'Black holes are not just empty voids, but instead are infinitely dense objects that warp the fabric of spacetime itself.',
  'The universe is thought to contain dark matter, which is a type of matter that does not interact with light or any other form of electromagnetic radiation and is currently only detectable through its gravitational effects.',
  'The universe is thought to have begun with the Big Bang, a massive explosion that occurred approximately 13.8 billion years ago and marked the beginning of the universe as we know it.',
  'The expansion of the universe is accelerating, and scientists currently attribute this acceleration to the presence of a mysterious force called dark energy.',
  'The universe is estimated to contain over 100 billion galaxies, each with billions upon billions of stars.',
  'The observable universe is over 90 billion light-years in diameter, but the entire universe may be much larger than this.',
  'The universe is thought to be around 13.8 billion years old, and the oldest known object in the universe is a galaxy called GN-z11, which is estimated to have formed just 400 million years after the Big Bang.',
  'The universe contains vast clouds of gas and dust that give rise to stars and galaxies, and these clouds can stretch for hundreds of light-years across.',
  'There are thought to be millions of black holes scattered throughout the universe, many of which have yet to be discovered.',
  'The cosmic microwave background radiation, which is thought to be the residual heat left over from the Big Bang, can be detected as a faint static on old television sets.',
  'The Pillars of Creation, a famous image of the Eagle Nebula captured by the Hubble Space Telescope, depicts massive columns of gas and dust that are currently being eroded by the radiation from nearby stars.',
  'The sun produces more energy in a single second than all of humanity has produced over the course of history.',
  'The universe is full of incredibly bright objects, such as quasars and blazars, that are powered by supermassive black holes at the centers of galaxies.',
  'The reason why the observable universe is more light-years in diameter than the age of the universe is because the universe has been expanding since the Big Bang, causing distant objects to move away from us as the light from them travels towards us.',
];
